### ISSUE TITLE
sv-bin-x86.zip archive corrupt

### ISSUE THREAD

**Issue by jangrewe** [nQuake/server-linux#1]
In a Docker container using alpine:latest as the base, the install scripts fails to extract the zip file.
I can open the zip file on my Windows machine and Debian box, and re-recreating the zip from the extracted files on one of those machines also succeeds in the Docker container.
All other zips can be extracted just fine.

Can you please recreate the zip file and update it on the mirrors?

Thanks!

```
unzip sv-bin-x86.zip
Archive:  sv-bin-x86.zip
replace ktx/qwprogs.so? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: ktx/qwprogs.so
error:  zipfile probably corrupt (illegal instruction)
```

**Comment by niclaslindstedt** [comment]
I used the Ubuntu zip package now to zip the files. Hopefully it should work. Sorry for this incredible delay.

**Comment by jangrewe** [comment]
Thanks =)
