### ISSUE TITLE
QTV 'admin' password

### ISSUE THREAD

**Issue by meag** [nQuake/server-linux#11]
During installation, the user is prompted for the QTV admin password.
This is then used as mvdsv's (non-admin) QTV password, required by connecting QTV servers.
We then also use it as the QTV admin password for QTV but not the connection password, so QTV fails to connect.

Not sure which way to fix this, depending on what the intention of the question was supposed to be.

**Comment by liback** [comment]
I suggest qtv_password (i.e. the MVDSV password) is left blank and the installer password really only used for QTV admin access.

Not sure if this would be acceptable for server admins though?

**Comment by meag** [comment]
Can't see any problem with that, as long as the tcp ports are firewalled.  So the advice would be to only open tcp port 28000, udp ports 28501->2850x & 30000 for qwfwd.  And to set a password before opening tcp ports 28501 etc.
