### ISSUE TITLE
QTV is run with nquakesv as the working directory?

### ISSUE THREAD

**Issue by meag** [nQuake/server-linux#15]
The old scripts used to change directory to ./qtv/ and then run qtv.bin
The new scripts run qtv.bin by absolute address, so the working directory is still the location of ./start_servers.sh
This pretty much breaks QTV http:// access - no css/images etc, and the 'demos' symbolic link is in the wrong place so no demos are available unless a new link created in the root nquakesv directory.

**Comment by liback** [comment]
Now changes work dir for both QTV and QWFWD before execution.

Verified that QTV web looks OK and that QTV seems to work in general (apart from demos as i'm not sure of an easy way to trigger recording alone :})
