### ISSUE TITLE
./mvdsv: 1: ./mvdsv: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by trumad** [nQuake/server-linux#3]
Hey - thanks so much for this easy to setup Quake server!

I'm attempting to run it on a raspberry pi, with Raspbian Jessie. I get this error when I run the start servers shell script:

./mvdsv: 1: ./mvdsv: Syntax error: "(" unexpected

When I try running mvdsv directly, I get this error:

 ./mvdsv: cannot execute binary file: Exec format error

My guess is that mvdsv is not compatible with Rasbian/debian perhaps? I hope that's not the issue, because I've looked high and low for a raspbian mvdsv build and haven't been able to find one.

**Comment by nvtkaszpir** [comment]
I'm affraid nquake is linux i386/amd64 architecture, while raspberry pi is armv7l.
So you would have to compile mvdsv+ ktx from sources under your raspberry

**Comment by trumad** [comment]
Hey, just to let everyone know I was able to find a compiled RPI binary here:

https://web.archive.org/web/20160509141340/http://files.quake.ie/linux/quake/mvdsv-ktx-raspberrypi.zip

Downloading that, and following the instructions here: http://www.recantha.co.uk/blog/?p=9962 saved me having to learn how to compile from source. I'll learn some day, I promise! Thanks for your help.

**Comment by nvtkaszpir** [comment]
Actually mvdsv and ktx are undergoing changes and those projects may provide compiled binaries for multiple platforms within few weeks.
