### ISSUE TITLE
Update maps

### ISSUE THREAD

**Issue by liback** [nQuake/server-linux#32]
Currently included maps in ~~sv-maps.zip~~ nquakesv:
```
2bfree.bsp
a2.bsp
aerowalk.bsp
amphi.bsp
arena3.bsp
arenax.bsp
barrel.bsp
blessed.bsp
bloodfest.bsp
boom.bsp
bravado.bsp
bravadob5.bsp
bsdm6.bsp
capit.bsp
catwalk2.bsp
cmt1b.bsp
cmt2.bsp
cmt3.bsp
cmt4.bsp
cmt5b.bsp
cpm1qw.bsp
cpm3a.bsp
cpm3qw.bsp
ctf1.bsp
ctf2.bsp
ctf2m1.bsp
ctf2m2.bsp
ctf2m3.bsp
ctf2m4.bsp
ctf2m5.bsp
ctf2m6.bsp
ctf2m7.bsp
ctf2m8.bsp
ctf3.bsp
ctf4.bsp
ctf5.bsp
ctf6.bsp
ctf7.bsp
ctf8.bsp
dad.bsp
death32c.bsp
debello.bsp
del1.bsp
dm1.bsp
dm2.bsp
dm2dmm4.bsp
dm3.bsp
dm3hill.bsp
dm4.bsp
dm4dmm4.bsp
dm4ish.bsp
dm5.bsp
dm5a.bsp
dm6.bsp
dm6dmm4.bsp
dmz1++.bsp
doomed.bsp
dungeonsurf.bsp
e2m2.bsp
e3m7.bsp
end.bsp
endif.bsp
escape2a.bsp
fmc.bsp
four.bsp
frenzy.bsp
frobodm2.bsp
genocide.bsp
gym.bsp
hate.bsp
head-shot.bsp
head.bsp
hook.bsp
hoppa2.bsp
jqdf1.bsp
jqdf2.bsp
jqdf3.bsp
jqfs1.bsp
jqfs2.bsp
jqfs3.bsp
jqrace1.bsp
kjdm7.bsp
leaks.bsp
monsoon.bsp
mvdsv-kg.bsp
oldcrat.bsp
outpost.bsp
pdm18.bsp
pkeg.bsp
pkeg1.bsp
pound.bsp
povdmm4.bsp
povdmm4b.bsp
pushdmm4.bsp
q1q3almostlost.bsp
q1q3cpm4_beta4.bsp
q1q3evolution_beta2.bsp
q1q3hektik.bsp
q1q3monsoon.bsp
q1q3ospdm5.bsp
q1q3phrantic.bsp
q1q3solid.bsp
q1q3thunderstruck.bsp
q1q3vertical_beta5.bsp
q3dm6ish.bsp
q3dm6qw.bsp
qcon1.bsp
qtdm3.bsp
race1.bsp
race10.bsp
race11.bsp
race12.bsp
race2.bsp
race3.bsp
race4.bsp
race5.bsp
race6.bsp
race7.bsp
race8.bsp
race9.bsp
rampage.bsp
rampcity.bsp
rawspeed.bsp
rf2test.bsp
rj3.bsp
rwild.bsp
sacredb1.bsp
schduel.bsp
schloss.bsp
shifter.bsp
shine.bsp
skull.bsp
slide1.bsp
slide2.bsp
slide3.bsp
slide4.bsp
slide5.bsp
slide6.bsp
slide7.bsp
slide8.bsp
slide9.bsp
slstart.bsp
softbox.bsp
speed.bsp
speedrush.bsp
spinev2.bsp
spitfire.bsp
subslide.bsp
subterfuge.bsp
travelert6.bsp
trick.bsp
trick1.bsp
tridm3.bsp
trix.bsp
tuhnu1.bsp
ukpak2.bsp
ultrav.bsp
vdm3v3.bsp
zjumps.bsp
ztndm3.bsp
ztndm3q.bsp
ztndm4.bsp
ztndm6.bsp
ztrain.bsp
ztricks.bsp
ztricks2.bsp
```

**Comment by liback** [comment]
Potential changes:

Remove:
bravadob5 (given that bravado is the latest n greatest)

Add:
Shifter (TD main pool)
Toxicity_test2 (TD main pool)
Dropout (TD custom pool)
Q1Q3toxicity_ql (TD custom pool)
Skull_td (TD custom pool)
Shifter_td (TD custom pool)
Travelert6_td (TD custom pool)
Ztndm1 (TD custom pool)
Ztndm2 (TD custom pool)
Ztndm5 (TD custom pool)

e3m3tdm (Get Quad pool - any other tem map versions?)

**Comment by mushis** [comment]
Im not into adding the TD custom pool maps, just because they're in the TD custom pool.

Bravado 
[Shifter](http://www.mediafire.com/file/bdoqbovbl28849i/shifter.zip/file)
[Dropout](https://www.quakeworld.nu/forum/topic/7285/duel2on2-map-drop-out) 
[Toxicity Final version](https://www.quakeworld.nu/forum/topic/7316/q1q3toxicity-final-version-release) this one is good.
[Excavation](https://www.quakeworld.nu/forum/topic/7268/excavation-1on12on2) - will ask for a final version of this one - very nice map (edit: not ready yet)
[burial](https://www.quakeworld.nu/forum/topic/7132/burial-by-foogs) - same as previous (edit: not ready yet)

**Comment by mushis** [comment]
anni's new dmm4 map

**Comment by mushis** [comment]
i meant ^anruin antemple anarena

**Comment by mushis** [comment]
you can close this

(i can't ??)

**Comment by liback** [comment]
Closed as per comment above.
