### ISSUE TITLE
QWFWD naming incorrect

### ISSUE THREAD

**Issue by liback** [nQuake/server-linux#33]
> mushiToday at 4:41 PM
> btw
> hello!
> https://www.quakeservers.net/quakeworld/servers/d=unnamed%20qwfwd/
> QuakeWorld Servers / QuakeServers.net
> Quake, QuakeWorld, Quake 2, Quake 3 and Quake 4 Servers.
> this needs to be checked out in nquakesv config
> the qwfwd's aren't being named correctly

**Comment by liback** [comment]
Not sure if related, but probably;

**start_servers.sh**
row 48,49: qwfwd/qwfwd.cfg is never generated due to incorrect arguments, should be $1, $2, $3 like in other similar functions?
row 53,54: there's a _set_ in front of the variables (hostname is one of them) which is not there for similar functions for other binaries (qtv for example)

**Comment by mushis** [comment]
"_set_" is ok
